### ISSUE TITLE
add a bin/csp_fixer.dart file

### ISSUE THREAD

**Issue by devoncarew** [sunglim/csp_fixer#1]
If you add a bin/csp_fixer.dart file, and an `executable` section in your pubspec that references it, people can do:

```
pub global activate csp_fixer
pub global run csp_fixer <filepath>
```

In order to use it on the command line.

Looks like a great library!

**Comment by sunglim** [comment]
Hey, dear @devoncarew  
hehe.. Thanks you for the advice :)  I will do!

I'm expecting people need this library to develop chrome app with polymer element.
The best would be .. to evolute like a Grunt vulcanize.

**Comment by sunglim** [comment]
Fixed. from version 0.1.0
