### ISSUE TITLE
better algorithm?

### ISSUE THREAD

**Issue by sunglim** [sunglim/csp_fixer#5]
To replace `<script>`
Probably. it might better to use linear search, instead of dom parser.

N = length of html file.
Linear search = O(log(N));
Dom parser = ? (this does more job. it must be expensive)

But we should be careful about `<script>` inside of comment(ie,. `<--   <script>foo</script> -->`)

**Comment by ussuri** [comment]
I think purely textual analysis of code would be very, very unreliable and could generate problematic output, especially if the input source has errors, e.g.:

``` html
<body>
...
<script>
  some code
  ...
 <!-- The author forgot to add a closing </script> here -->

 <div>...</div>

 <script>
   some other code
</script>
</body>
```

Also, you would have to come up with a very robust parser of all the possible forms of the `<script>` tag (`id`, `src`, `type`, `language` and other attributes).

All-in-all, I don't think it's worth it.

**Comment by sunglim** [comment]
@ussuri  Thank you for your opinion. thesedays I'm studying algorithm . so I was a little sensitive about the performance :) 
Yes, We also need to handle attributes which can be obstables :/
